name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-gcc
        pacman -S --noconfirm mingw-w64-x86_64-pkg-config
        pacman -S --noconfirm mingw-w64-x86_64-gtk3
        pacman -S --noconfirm mingw-w64-x86_64-SDL2_image
        pacman -S --noconfirm mingw-w64-x86_64-libpng

    - name: Build
      run: |
        gcc -O2 -Wall -o "PalApply v2.exe" gui.c palapply.c `pkg-config --cflags --libs gtk+-3.0 SDL2_image | sed 's/-lSDL2main//g'` -lpn -mwindows
